env = GDK_SCALE,2

# Good compromise for 27" or 32" 4K monitors (but fractional!)
# env = GDK_SCALE,1.75
# monitor=,preferred,auto,1.666667
# monitor = DP-1,preferred,auto,1.666667

monitor=,preferred,2880x1800@120,1.8
monitor = DP-6, preferred, auto, 1.875 # left port
monitor = DP-1, preferred, auto, 1.6 # right port
